name: CI

on: push

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Go to the commit that triggered workflow
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle
      - name: Run unit tests
        run: ./gradlew test
      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'