name: CI

on: push

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle
      - name: Run unit tests
        run: ./gradlew test
      - name: Report unit tests results
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: app/build/reports/tests/testDebugUnitTest/index.html